-- MySQL Script generated by MySQL Workbench
-- Sat Jun 13 16:23:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`adreça`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adreça` (
  `carrer` INT NULL,
  `numero` INT NULL,
  `pis` VARCHAR(45) NULL,
  `ciutat` VARCHAR(45) NULL,
  `codi_postal` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codi_postal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveidors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveidors` (
  `NIF_proveidor` INT NOT NULL,
  `telf_proveidor` VARCHAR(45) NOT NULL,
  `fax_proveidor` VARCHAR(45) NOT NULL,
  `adreça_codi_postal` INT NOT NULL,
  PRIMARY KEY (`NIF_proveidor`),
  INDEX `fk_proveidors_adreça_idx` (`adreça_codi_postal` ASC) VISIBLE,
  CONSTRAINT `fk_proveidors_adreça`
    FOREIGN KEY (`adreça_codi_postal`)
    REFERENCES `mydb`.`adreça` (`codi_postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ulleres` (
  `marca` VARCHAR(45) NOT NULL,
  `muntura` VARCHAR(10) NOT NULL COMMENT 'Pot ser:\n- flotant\n- pasta\n- metàl·lica',
  `preu` INT NOT NULL,
  `proveidors_NIF_proveidor` INT NOT NULL,
  INDEX `fk_ulleres_proveidors1_idx` (`proveidors_NIF_proveidor` ASC) VISIBLE,
  PRIMARY KEY (`marca`),
  CONSTRAINT `fk_ulleres_proveidors1`
    FOREIGN KEY (`proveidors_NIF_proveidor`)
    REFERENCES `mydb`.`proveidors` (`NIF_proveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `nom_client` VARCHAR(45) NOT NULL,
  `telefon_client` INT NOT NULL,
  `correu_client` VARCHAR(255) NOT NULL,
  `registre_client` DATETIME NOT NULL,
  `adreça_codi_postal` INT NOT NULL,
  PRIMARY KEY (`nom_client`),
  INDEX `fk_clients_adreça1_idx` (`adreça_codi_postal` ASC) VISIBLE,
  CONSTRAINT `fk_clients_adreça1`
    FOREIGN KEY (`adreça_codi_postal`)
    REFERENCES `mydb`.`adreça` (`codi_postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleats` (
  `id_empleat` INT NOT NULL,
  PRIMARY KEY (`id_empleat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vidres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vidres` (
  `graduació_D` DECIMAL(4) NOT NULL,
  `graduació_E` DECIMAL(4) NOT NULL,
  `color_D` VARCHAR(15) NOT NULL,
  `color_E` VARCHAR(15) NULL,
  `ulleres_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ulleres_marca`),
  CONSTRAINT `fk_vidres_ulleres1`
    FOREIGN KEY (`ulleres_marca`)
    REFERENCES `mydb`.`ulleres` (`marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleats_has_ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleats_has_ulleres` (
  `empleats_id_empleat` INT NOT NULL,
  `ulleres_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`empleats_id_empleat`, `ulleres_marca`),
  INDEX `fk_empleats_has_ulleres_ulleres1_idx` (`ulleres_marca` ASC) VISIBLE,
  INDEX `fk_empleats_has_ulleres_empleats1_idx` (`empleats_id_empleat` ASC) VISIBLE,
  CONSTRAINT `fk_empleats_has_ulleres_empleats1`
    FOREIGN KEY (`empleats_id_empleat`)
    REFERENCES `mydb`.`empleats` (`id_empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleats_has_ulleres_ulleres1`
    FOREIGN KEY (`ulleres_marca`)
    REFERENCES `mydb`.`ulleres` (`marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
